# Statistics in Data Science Webinar Series

## Week 3: Statistical Experiments and Significance Testing

February 20, 2021
<br>

Angela Gaetano, M.S. Data Science, Manager of Data Science, Medtronic
<br>
Sneha Thanasekaran, M.S. Information Systems, Data Scientist, Medtronic
<br>
Sowmya Uk
<br>
Shaivya Kodan

<br>

Data files: https://drive.google.com/drive/u/1/folders/1kvVDL6ps5q8vQr58j9WjMCrYWostiZKy

### Topics
1. Introduction: Why Run Statistical Experiments?
2. Variability in Estimates
3. Hypothesis Testing
 1. Hypothesis Testing Framework: Step-by-Step Guide
 2. Choosing the Appropriate Statistical Test, Testing Assumptions,and Interpretting the Results (i.e., "Significance")
 3. Parametric tests including t-tests, ANOVA, chi-squared tests
 4. Non-Parametric tests including Mann Whitney, Kruskal-Wallis, Wilcoxon Signed Rank Tests 
4. Supporting your Statistical Experiments with additional evidence
 1. Resampling - Permutation Testing
 2. Power and Sample Size
5. A/B Testing: A Common Application of Statistical Experimentation

### Introduction: Why Run Statistical Experiments?

Statistics is an attainable and yet powerful tool for the Data Scientist. By leveraging principles of mathematical probability and inference, we can provide answers to meaningful questions that would otherwise be impossible to answer in our world of large numbers and possibilities. By finding ways to harness samples to represent broader populations and themes, we can advance the learnings of the scientific community. Some say, "Data is Power." I say, "Statistics with Power is Significant!"
<br>
<br>

Not only will this lesson enable you to run your own statistical experiments, but it will also empower you to look at the world with a scientific eye, being able to research and read clinical studies and understand what they truly mean. For example, with nothing more than a basic level of expertise in statistical experiments and hypothesis testing, anyone can learn more about the Covid-19 Vaccine Clinical Trials, and how to interpret the results. Understanding these principles of experimentation can be useful to anyone in our day to day lives!

#### Principles of Experiments

* **Controlling** ‚Äì control for differences between groups other than what is being tested for
* **Randomization** ‚Äì helps account for uncontrollable confounding variables
* **Replication** ‚Äì be able to perform tests on multiple subjects, or even replicate an entire study
* **Blocking** ‚Äì intentional grouping of individuals with common uncontrollable confounding variable, and then randomly assign equal numbered subsets into the treatment groups

### Variability in Estimates

* **Point Estimate**: the sample estimate measure of the population parameter (e.g., $\bar x$  is the point estimate for $\mu$   , $\hat p$ is the estimate for $p$)
* The Point Estimate will slightly vary each time you take a new sample of the population (e.g., sampling variation)
* If you take samples and measure the point estimate many times, you can build up the sampling distribution of the point estimate. ‚ÄúUnderstanding the sampling distribution is central to understanding statistical inference.‚Äù
* The standard error of the estimate is the standard deviation of the sampling distribution
* From a single sample, we can use the following equation to calculate standard error for the sample mean: $ùëÜùê∏=  \frac{œÉ}{\sqrt[]{n}}$ (use $s$ when $œÉ$ is unknown)

![test pic](https://drive.google.com/uc?id=1_J9ef_vy-EI81yRYLZIh3kOWVh-qKsLV)

### Hypothesis Testing: Introduction

* Takes the position of the skeptic:
 + I will not be convinced that there is any difference unless strong evidence is presented in favor of that alternative
 + Innocent until proven guilty
* Formal testing using p-values
 + The p-value is the probability of observing data at least as favorable to the alternative hypothesis as our current data set, if the null hypothesis is true
 + The lower the p-value, the stronger the data favor the alternative hypothesis
 + Why 0.05 significance level (Œ± = 0.05)? It turns out to be the most common ‚Äúnatural threshold‚Äù for human skepticism. For more info, visit www.openintro.org/why05


![image](https://drive.google.com/uc?export=view&id=1XCgrFhPAinvsmYJC_pSomd5mWHwh3oCA)

### Hypothesis Testing: Step-by-Step

1. Define the null and alternative hypothesis
* Null hypothesis is always the one that contains equality
* Alternative implies inequality (or ‚Äúdifference‚Äù)

2. Set the significance Level, Œ±
* 0.05 is most commonly used. Use 0.01 if you want to make the test more strict

3. Select an appropriate statistical test
* Consider the type of data in the study
 + How Many groups of data? Are the data _paired_? Is the output you are trying to measure Continuous, Binary, or Categorical?
* Understand whether you need to test for assumptions. Typical assumptions of parametric tests are
 + Samples are independent and unbiased
 + Data is approximately normal (within all groups). Can use Anderson-Darling test or Shapiro-Wilks test (two most commonly used). If sample size is large enough and appears approximately normal with no significant skewness, no need to test assumption further
 + If there is more than one group of data, need to know whether the variances are equal. Can use an F test or Levene's test

4. Decide one or two tailed
* A one-tailed test implies that the alternative hypothesis is a directional inequality (i.e., "greater than" or "less than"). Only use a one-tailed test if the intention of the experiment is based on a pre-stated suspicion of direction. Otherwise, always assume two-tailed (i.e., alternative hypothesis is "not equal"). Most statistical functions assume two-tailed default parameter

5. Run the Statistical Test
* Usually can be done with one line of code that takes the data as input as well as other specific testing parameters

6. Interpret the output: Decide whether to Reject or Fail to Reject the Null hypothesis
* Use the p-value to determine the outcome of the test. If the p-value < Œ±, Reject the Null Hypothesis, proving the alternative. Otherwise, Fail to Reject the Null, conveying there was not enough evidence to reject the null

### Choosing the Appropriate Statistical Test, Testing Assumptions,and Interpretting the Results (i.e., "Significance")

To choose the appropriate statistical test, you must ask certain key questions:
1. What is the data type of the response? i.e., what data type is the value you are measuring? Continous, Binary, or Categorical?
2. What is the data type of the input? Binary input implies you are dealing with two groups, "A" and "B". Categorical input implies you have multiple groups. Continuous input implies you are interested in correlation
 * If the input in Binary, and your response is continuous, ask if the data are "_paired_"
 * If the input is Binary or Categorical, and your response is continuous, test whether the variances between the groups are equal
 * If the input is Continous, run a correlation test using either Pearson's, Spearman's, or Kendall's depending on results of (3) below
3. Do your data satisfy assumptions for a Parametric test, or do you need to choose a Non-Parametric test?
 * Recall assumptions for parametric tests from above


Below are some flowcharts created by one of my colleagues to assist you in your decision-making when your inputs are either Binary or Categorical (Credit: Alice Townsend: [LinkedIn](https://www.linkedin.com/in/alice-townsend-04474a77/)).

![](https://drive.google.com/uc?id=1grEMp76x_RNng2faf-wp-IVsbkvtVXjY)

![](https://drive.google.com/uc?id=1TMn7Qih_8zvvJ2DqUpJZvxSYZOD8dRVP)

### Let's work through some examples

In [2]:
import scipy.stats as stats
import numpy as np 
import pandas as pd

## Exercise 1: Are Mean Crime Rates different between the North and the South?

In [4]:
url = 'https://drive.google.com/file/d/1RxU0OyMgyH4O843AT7OrczjHilhYrnCG/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
crime = pd.read_csv(path)
crime.head()

   CrimeRate  Youth  Southern  ...  HighYouthUnemploy10  Wage10  BelowWage10
0       45.5    135         0  ...                    1     632          142
1       52.3    140         0  ...                    1     521          210
2       56.6    157         1  ...                    0     359          256
3       60.3    139         1  ...                    0     510          235
4       64.2    126         0  ...                    1     660          162

[5 rows x 27 columns]

### Step 1: Define the null the alternative hypothesis

$H_{0}: \mu_{N} - \mu_{S} = 0$

$H_{A}: \mu_{N} - \mu_{S} \neq 0$

### Step 2: Set Significance Level

$\alpha = 0.05$

### Step 3: Select the appropriate statistical test

#### What type of variable is the "input"?

The input is a binary classification, "North" vs "South". So, the answer is **Binary**

#### What type of variable is the "response"?

The response is "Crime Rate," which is a **continuous** value

#### Is the response paired?

**No**, the responses are not paired by the groups; they are independent groups.

#### Does the response follow a normal distribution in both groups?

Need to either test for Normality with an Anderson-Darling hypothesis test, or assume normality based on other descriptive details of the data (sample size, skewness, etc.)

In [5]:
SouthCrime = crime.loc[(crime.Southern == 1)] #South
SouthCrime.describe()

        CrimeRate       Youth  ...      Wage10  BelowWage10
count   16.000000   16.000000  ...   16.000000    16.000000
mean   100.681250  148.687500  ...  515.125000   233.062500
std     22.588233   13.174312  ...   92.404094    26.611949
min     56.600000  127.000000  ...  359.000000   170.000000
25%     94.000000  141.250000  ...  468.750000   226.750000
50%    101.450000  148.000000  ...  505.000000   243.000000
75%    112.650000  157.000000  ...  553.000000   250.250000
max    145.400000  177.000000  ...  703.000000   257.000000

[8 rows x 27 columns]

In [6]:
NorthCrime = crime.loc[(crime.Southern == 0)] #North
NorthCrime.describe()

        CrimeRate       Youth  ...      Wage10  BelowWage10
count   31.000000   31.000000  ...   31.000000    31.000000
mean   103.906452  133.354839  ...  635.677419   172.258065
std     31.957555    8.526619  ...   63.991868    25.464966
min     45.500000  119.000000  ...  499.000000   126.000000
25%     80.200000  126.000000  ...  590.000000   155.000000
50%    104.300000  132.000000  ...  639.000000   169.000000
75%    129.800000  140.000000  ...  681.500000   185.500000
max    161.800000  152.000000  ...  748.000000   234.000000

[8 rows x 27 columns]

We can tell from the CrimeRate descriptions that the data are very centered (not skewed), and the sample size for the South is questionable at n = 16, and the sample size for the North is decent at n = 31. With all of this information, we can assume normality.

#### Are variances between groups equal?

Need to run an F-test to test for equal variances.

In [7]:
#perform F-test
stats.f_oneway(NorthCrime['CrimeRate'],SouthCrime['CrimeRate'])

F_onewayResult(statistic=0.12900371305145147, pvalue=0.7211471608862728)

p-value > 0.05, so we Fail To Reject the Null Hypothesis. The variances are equal.
<br>
So, the appropriate statistical test to test our original hypothesis is a **Student's t-test.** Yay for normal, easy data!

### Step 4: Decide One or Two Tailed

Two-tailed

### Step 5: Run the Statistical Test

In [8]:
stats.ttest_ind(NorthCrime['CrimeRate'],SouthCrime['CrimeRate']) ## from scipy.stats

Ttest_indResult(statistic=0.35917086887921945, pvalue=0.7211471608862718)

p-value > 0.05, so we Fail To Reject the Null Hypothesis. **There is no difference in crime rate between the Northern and Southern regions.**


<center>
<img src="https://drive.google.com/uc?export=view&id=1Nggz1m4TJ8wBvw7--xDsDEhjV9jDeUmm"  align="center"></center>

## Exercise 2: Is there a difference in ticket fare between Titantic survivors and non-survivors?

In [9]:
url = 'https://drive.google.com/file/d/1Yyyd9rnsaIpbeAFcnrgtnCs1lm9fxKbP/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
titanic = pd.read_csv(path)
titanic

      pclass  survived  Residence  ... body               home.dest  Gender
0          3         0          0  ...                                    0
1          3         0          0  ...          East Providence, RI       0
2          3         0          0  ...  190     East Providence, RI       0
3          3         1          0  ...          East Providence, RI       1
4          3         1          2  ...       Norway Los Angeles, CA       1
...      ...       ...        ...  ...  ...                     ...     ...
1304       3         0          2  ...  328                               1
1305       3         0          2  ...                                    1
1306       3         0          2  ...  304                               0
1307       3         0          2  ...                                    0
1308       3         0          2  ...                                    0

[1309 rows x 15 columns]

In [10]:
titanic.dtypes

pclass        int64
survived      int64
Residence     int64
name         object
age          object
sibsp         int64
parch         int64
ticket       object
fare         object
cabin        object
embarked     object
boat         object
body         object
home.dest    object
Gender        int64
dtype: object

#### Need to clean data to measure Fare - convert to numeric

In [11]:
titanic = titanic[titanic.fare != ' '] # found a blank fare value by sorting the dataframe by fare
titanic['fare'] = titanic['fare'].astype('float')
titanic.dtypes

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

pclass         int64
survived       int64
Residence      int64
name          object
age           object
sibsp          int64
parch          int64
ticket        object
fare         float64
cabin         object
embarked      object
boat          object
body          object
home.dest     object
Gender         int64
dtype: object

### Step 1: Define the null the alternative hypothesis

$H_{0}: \mu_{S} - \mu_{N} = 0$

$H_{A}: \mu_{S} - \mu_{N} \neq 0$

### Step 2: Set Significance Level

$\alpha = 0.05$

### Step 3: Select the appropriate statistical test

#### What type of variable is the "input"?

The input is a binary classification, "Survivor" vs "Non-Survivor". So, the answer is **Binary**

#### What type of variable is the "response"?

The response is "Fare," which is a **continuous** value

#### Is the response paired?

**No**, the responses are not paired by the groups; they are independent groups.

#### Does the response follow a normal distribution in both groups?

Need to either test for Normality with a Shapiro-Wilk hypothesis test, or assume normality based on other descriptive details of the data (sample size, skewness, etc.)

In [12]:
SurvivorFares = titanic.loc[(titanic.survived == 1)] #Survivors
SurvivorFares.describe()

           pclass  survived   Residence  ...       parch        fare      Gender
count  500.000000     500.0  500.000000  ...  500.000000  500.000000  500.000000
mean     1.962000       1.0    1.228000  ...    0.476000   49.361184    0.678000
std      0.872972       0.0    0.870363  ...    0.776292   68.648795    0.467711
min      1.000000       1.0    0.000000  ...    0.000000    0.000000    0.000000
25%      1.000000       1.0    0.000000  ...    0.000000   11.214600    0.000000
50%      2.000000       1.0    2.000000  ...    0.000000   26.000000    1.000000
75%      3.000000       1.0    2.000000  ...    1.000000   57.750000    1.000000
max      3.000000       1.0    2.000000  ...    5.000000  512.329200    1.000000

[8 rows x 7 columns]

#### We can tell there is significant skewness in fare, so we need to run a test for normality

In [13]:
stats.shapiro(SurvivorFares['fare'])

(0.607525110244751, 4.0718098693662947e-32)

#### Since the p-value is small, we reject the null hypothesis that the fare data is normally distributed. Therefore, we need to use a non-parametric test. There is no need now to test the other data group's normality, since it already failed for the first group, but it is described below for visibility

In [14]:
NonSurvivorFares = titanic.loc[(titanic.survived == 0)] #Non-Survivors
NonSurvivorFares.describe()

           pclass  survived   Residence  ...       parch        fare      Gender
count  808.000000     808.0  808.000000  ...  808.000000  808.000000  808.000000
mean     2.500000       0.0    1.466584  ...    0.329208   23.353831    0.157178
std      0.745079       0.0    0.727490  ...    0.912824   34.145096    0.364194
min      1.000000       0.0    0.000000  ...    0.000000    0.000000    0.000000
25%      2.000000       0.0    1.000000  ...    0.000000    7.854200    0.000000
50%      3.000000       0.0    2.000000  ...    0.000000   10.500000    0.000000
75%      3.000000       0.0    2.000000  ...    0.000000   26.000000    0.000000
max      3.000000       0.0    2.000000  ...    9.000000  263.000000    1.000000

[8 rows x 7 columns]

#### Based on these steps, the appropriate statistical test is the Mann-Whitney rank test to compare medians

### Step 4: Decide One or Two Tailed

Two-tailed

### Step 5: Run the Statistical Test

In [15]:
stats.mannwhitneyu(SurvivorFares['fare'],NonSurvivorFares['fare']) ## from scipy.stats

MannwhitneyuResult(statistic=131452.5, pvalue=1.0885770643327487e-26)

p-value < 0.05, so we **Reject the Null Hypothesis. There is a difference in fares between the survivors and non survivors of the Titanic.**

## Exercise 3: Is there a difference in proportion of favorite ice cream flavors between females and males? Or said another way, is there a difference in proportion of gender between different favorite ice cream flavors? Are these two factors of gender and ice cream flavors dependent of each other?

In [ ]:
url = 'https://drive.google.com/file/d/1rbJNoqy9y27BKfIfNeCoxnYNska9DQBV/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
ice_cream = pd.read_csv(path)
ice_cream.head()

    id  female  ice_cream  video  puzzle
0   70       0          2     47      57
1  121       1          1     63      61
2   86       0          3     58      31
3  141       0          3     53      56
4  172       0          1     53      61

### Step 1: Define the null the alternative hypothesis

$H_{0}$: input and response are independent

$H_{A}$: input and response are not independent

### Step 2: Set Significance Level

$\alpha = 0.05$

### Step 3: Select the appropriate statistical test

#### What type of variable is the "input"?

Let's choose which variable we will consider as the "input". We will choose gender as "input," and favorite ice cream as the "Response." So, the input is a binary classification, "female" vs "male". So, the answer is **Binary**

#### What type of variable is the "response"?

The response is "ice cream flavor," which is a **categorical** value


#### Are any counts less than 5?

Need to describe dataset using a **contigency table** to check. SEE BELOW.

### Step 4: Decide One or Two Tailed

N/A

In [ ]:
data_crosstab = pd.crosstab(ice_cream['female'], 
                            ice_cream['ice_cream'],  
                               margins = False)
data_crosstab

ice_cream   1   2   3
female
0          47  15  29
1          48  32  29

#### Are any counts less than 5?

No
<br>
<br>
So we should use **Pearson's Chi-Squared Test for Independence**

### Step 5: Run the Statistical Test

In [ ]:
stats.chi2_contingency(data_crosstab)

(4.57653239842952, 0.10144219001975929, 2, array([[43.225, 21.385, 26.39 ],
        [51.775, 25.615, 31.61 ]]))

p-value is .10, which is greater than .05, so we **fail to reject the null hypothesis. Ice Cream favorite flavors and gender are independent.**

## Exercise 4: Is there a relationship between video game scores and puzzle scores?

### Step 1: Define the null the alternative hypothesis

$H_{0}$: video game scores and puzzle scores are not related

$H_{A}$: video game scores and puzzle scores are related


### Step 2: Set Significance Level

$\alpha = 0.05$

### Step 3: Select the appropriate statistical test

#### What type of variable is the "input"?

Let's choose which variable we will consider as the "input". We will choose puzzle scores as "input," and video game scores as the "Response." So, the input is **Continuous**

#### What type of variable is the "response"?

The response is "video game scores," which is a **continuous** value

#### Are the two datasets normally distributed?
Need to test for normality.

In [ ]:
stats.shapiro(ice_cream['video'])

(0.9852479696273804, 0.03476548567414284)

Video game scores are not normally distributed.

So, we should use **Spearman's Rank-order Test for Correlation**, which is the nonparametric version of Pearson's Correlation test. (Note: if the data was ordinal, not continuous, you would choose Kendall's rank-order test.)

### Step 4: Decide One or Two Tailed

Comparing two things: two-tailed

### Step 5: Run the Statistical Test

In [ ]:
rho, pval = stats.spearmanr(ice_cream['puzzle'], ice_cream['video'])
rho

0.4807848961450622

In [ ]:
pval

5.784303749592024e-13

The p-value is less than 0.05, so we **Reject the Null hypothesis. Puzzle scores and video games scores are related (i.e., there is an association between video game scores and puzzle scores).**

## Exercise 5: Is there a difference in puzzle scores between groups of favorite ice cream flavors?

### Step 1: Define the null the alternative hypothesis

$H_{0}$: there is no difference in puzzle scores between ice cream groups

$H_{A}$: at least one group is different

### Step 2: Set Significance Level

$\alpha = 0.05$

### Step 3: Select the appropriate statistical test

#### What type of variable is the "input"?

The input is a category, Ice Cream Flavor (1, 2, or 3). So, the answer is **Categorical**

#### What type of variable is the "response"?

The response is "puzzle scores," which is a **continuous** value


#### Does the response follow a normal distribution in all groups?

Need to either test for Normality with a Shapiro-Wilk hypothesis test, or assume normality based on other descriptive details of the data (sample size, skewness, etc.)

In [ ]:
IceCream_1 = ice_cream.loc[(ice_cream.ice_cream == 1)] #1
IceCream_1.describe()

               id     female  ice_cream      video     puzzle
count   95.000000  95.000000       95.0  95.000000  95.000000
mean   107.652632   0.505263        1.0  51.705263  52.031579
std     59.805495   0.502625        0.0   8.926263   9.972785
min      2.000000   0.000000        1.0  34.000000  26.000000
25%     57.500000   0.000000        1.0  44.000000  46.000000
50%    113.000000   1.000000        1.0  53.000000  51.000000
75%    161.000000   1.000000        1.0  58.000000  61.000000
max    200.000000   1.000000        1.0  74.000000  71.000000

#### The data appears to not be very skewed. Since the sample size is 95, it is reasonable to assume normality

In [ ]:
IceCream_2 = ice_cream.loc[(ice_cream.ice_cream == 2)] #2
IceCream_2.describe()

               id     female  ice_cream      video     puzzle
count   47.000000  47.000000       47.0  47.000000  47.000000
mean    74.553191   0.680851        2.0  47.702128  47.319149
std     53.122012   0.471186        0.0  10.413025  10.836946
min      1.000000   0.000000        2.0  29.000000  26.000000
25%     35.500000   0.000000        2.0  39.500000  41.000000
50%     63.000000   1.000000        2.0  47.000000  46.000000
75%    121.500000   1.000000        2.0  54.500000  56.000000
max    173.000000   1.000000        2.0  69.000000  71.000000

#### The data appears to not be very skewed. Since the sample size is 95, it is reasonable to assume normality

In [ ]:
IceCream_3 = ice_cream.loc[(ice_cream.ice_cream == 3)] #3
IceCream_3.describe()

               id     female  ice_cream      video     puzzle
count   58.000000  58.000000       58.0  58.000000  58.000000
mean   109.810345   0.500000        3.0  55.448276  57.137931
std     52.832226   0.504367        0.0   9.794686   9.962118
min     14.000000   0.000000        3.0  26.000000  31.000000
25%     80.500000   0.000000        3.0  50.000000  51.250000
50%    101.500000   0.500000        3.0  58.000000  61.000000
75%    145.500000   1.000000        3.0  62.500000  66.000000
max    199.000000   1.000000        3.0  69.000000  71.000000

#### The data appears to have some skew. It is reasonable to test for normality on this group using the Shapiro Wilk test

In [ ]:
stats.shapiro(IceCream_3['puzzle'])

(0.9051462411880493, 0.0002601834130473435)

Since the p-value < .05, we **reject the null hypothesis that the data is normal. Therefore, we cannot use the Parametric One-Way ANOVA. The appropriate statistical test in this case is the Kruskal Wallis test to test whether the distributions are significantly different.**

### Step 4: Decide One or Two Tailed

N/A

### Step 5: Run the Statistical Test

In [ ]:
stats.kruskal(IceCream_1['puzzle'],IceCream_2['puzzle'],IceCream_3['puzzle'],) ## from scipy.stats

KruskalResult(statistic=23.480904220541486, pvalue=7.965011982009563e-06)

p-value < 0.05, so we **Reject the Null Hypothesis. There is a difference in puzzle score distributions between the groups of favorite ice cream flavors.**

<br>

#### Now, we should use a Dunn-Bonferroni post-hoc test to see which pairwise groups have significant differences in puzzle scores. (Note: when following an ANOVA parametric test, use Tukey's Honestly Significant Difference post-hoc test)

Scikit_posthocs documentation for Dunn-Bonferroni test: [https://scikit-posthocs.readthedocs.io/en/latest/generated/scikit_posthocs.posthoc_dunn/](https://scikit-posthocs.readthedocs.io/en/latest/generated/scikit_posthocs.posthoc_dunn/)

In [ ]:
# conda install -c conda-forge scikit-posthocs
# %pip install scikit_posthocs
import scikit_posthocs as sp

sp.posthoc_dunn(ice_cream,val_col = 'puzzle', group_col = 'ice_cream', p_adjust = 'bonferroni')

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

          1         2         3
1  1.000000  0.060432  0.004841
2  0.060432  1.000000  0.000005
3  0.004841  0.000005  1.000000

We can see from this resulting pairwise table of p-values that there is a significant difference in puzzle scores between ice cream flavor groups 1 and 3, and between 2 and 3, but not between 1 and 2.

## Exercise 6: Was cholesterol reduced after introducing a particular brand of margarine (margarine A)?

In [ ]:
url = 'https://drive.google.com/file/d/16PaXKkf2dd18l9ci-FP6M6XMmcppyM9F/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
cholesterol = pd.read_csv(path)
cholesterol.head()

   ID  Before  After4weeks  After8weeks Margarine
0   1    6.42         5.83         5.75         B
1   2    6.76         6.20         6.13         A
2   3    6.56         5.83         5.71         B
3   4    4.80         4.27         4.15         A
4   5    8.43         7.71         7.67         B

In [ ]:
chol_A = cholesterol.loc[(cholesterol.Margarine == 'A')]
chol_A.head()

   ID  Before  After4weeks  After8weeks Margarine
1   2    6.76         6.20         6.13         A
3   4    4.80         4.27         4.15         A
5   6    7.49         7.12         7.05         A
7   8    5.05         4.63         4.67         A
9  10    3.91         3.70         3.66         A

### Step 1: Define the null the alternative hypothesis

$H_{0}: \mu_{After} - \mu_{Before} = 0$

$H_{A}: \mu_{After} - \mu_{Before} < 0$

### Step 2: Set Significance Level

$\alpha = 0.05$

### Step 3: Select the appropriate statistical test

#### What type of variable is the "input"?

The input is a binary classification, "Before" vs "After". So, the answer is **Binary**

#### What type of variable is the "response"?

The response is "Cholesterol After 8 Weeks," which is a **continuous** value

#### Is the response paired?

**Yes**, the responses are paired between the groups; they are groups with before-after values that contain the same subjects in both.

#### Does the response follow a normal distribution in both groups?

Need to either test for Normality with a Shapiro-Wilk hypothesis test, or assume normality based on other descriptive details of the data (sample size, skewness, etc.)

In [ ]:
chol_A.describe()

              ID    Before  After4weeks  After8weeks
count   9.000000  9.000000     9.000000     9.000000
mean    9.888889  6.035556     5.550000     5.488889
std     5.230785  1.363232     1.320672     1.307282
min     2.000000  3.910000     3.700000     3.660000
25%     6.000000  5.050000     4.520000     4.450000
50%    10.000000  6.170000     5.560000     5.510000
75%    14.000000  7.340000     6.840000     6.820000
max    17.000000  7.670000     7.120000     7.050000

#### Since the sample size is small, it would be reasonable to test for normality

In [ ]:
stats.shapiro(chol_A['Before'])

(0.918092668056488, 0.376682847738266)

In [ ]:
stats.shapiro(chol_A['After8weeks'])

(0.9038563966751099, 0.2752096652984619)

#### Since the p-value > 0.05, we fail to reject the null hypothesis cholesterol data is normally distributed. Therefore, we can use a parametric test to compare means

#### Based on these steps, the appropriate statistical test is Student's paired t test to compare means. (Note: non-parametric version of this scenario is the Wilcoxon Signed Rank test)

### Step 4: Decide One or Two Tailed

One-tailed. Since we are testing for "<" based on the way we set up the hypothesis, it is a lower tailed test

### Step 5: Run the Statistical Test

In [ ]:
stats.ttest_rel(chol_A['After8weeks'],chol_A['Before']) ## from scipy.stats

Ttest_relResult(statistic=-10.300418405549777, pvalue=6.802292614929953e-06)

_Note: Since this is a one-sided test, and this version of scipy does not allow you to specify that, simply divide your pvalue by 2._

p-value < 0.05, so we **Reject the Null Hypothesis. There is a reduction in cholesterol after subjects started with Margarine A.**

### Supporting your Statistical Experiments with Additional Evidence

#### Resampling and Permutation Testing

Using permutation testing to resample your data grants you the opportunity to present more evidence of associations or differences in your data. This is an example of using statistical simulation to provide evidence to your experiments.

Consider the example of the Margarine Study, which is a paired study.

We can generate a *permutation distribution* by randomly assigning each subject's cholesterol to either the before or after categories, and then calculating the mean difference for each permutation. Because of its inherent randomness, the permutation distribution would have a mean around 0.  If margarine has no impact on cholesterol, we would expect the observed mean difference in our original study sample to be not much different from this randomized permutation sample. A permutation test tests this hypothesis and calculates a p-value.

![](https://drive.google.com/uc?id=1qXh0WazhMBUgGHWqndqNiI6WzoKlZ59t)

For more information, visit this online text: [https://statweb.stanford.edu/~tibs/stat315a/Supplements/bootstrap.pdf](https://statweb.stanford.edu/~tibs/stat315a/Supplements/bootstrap.pdf)

#### Power and Sample Size

**Power is the probability of rejecting the null hypothesis when, in fact, it is false.** Power is a way to reduce the likelihood of a Type II error, which is that you fail to reject the null even though the difference is present. Power is usually represented as $1 - \beta$.

![](https://drive.google.com/uc?id=1Z1VaPUHQwkPaXm4PToJqE4KUChrjTc2K)

Setting a power is a way for researchers to know how many subjects to enroll in the study in order to optimize the ability to detect a difference should one exist. In statistical experiments, it is recommended that the minimum power to your study be set to at least 80%, (i.e., $\beta = 0.2$). As sample size increases, so does the power of the study. There are many sample size calculators online.

### A/B Testing: A Common Application of Statistical Experimentation

A/B Testing is a common application of a statistical experiment, used often in the field of web development. You might have heard A/B Testing in the context of testing different UI Designs of a website, assigning a control group "A" to some website viewers, and a "treatment" group "B" to another set of website viewers. You can directly measure and compare metrics of interest between these groups, for example, how many converted to a "sale", or "conversion rate." 

A/B test includes the application of Statistical Hypothesis Testing 

![](https://drive.google.com/uc?id=1I5uoJm3UMJrH0iKxx1K3u9tzKjPX293l)

Let‚Äôs see an example...

Imagine that you are running a UI experiment where you want to understand the difference between the time spent on your initial layout vs a new layout. (let‚Äôs imagine you want to understand the impact of having a vertical layout Vs a Horizontal layout )

Imagine we are using the average session time (time spent on the page) as our metric to analyze the result of the A/B test. We aim to understand if the new design of the page gets more attention from the users and increase the time they spend on the page.

In [ ]:
import pandas as pd
import statsmodels.api as sm
import numpy as np
from scipy import stats
import seaborn as sns
url = 'https://drive.google.com/file/d/1Z43HPoX916GEJ5sMZs-6fLnvsTW8P3BV/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
design = pd.read_csv(path, sep=';')
design.head()
#Time is in minutes

         Page  Time
0  Old design  0.35
1  New design  1.20
2  Old design  0.80
3  New design  1.20
4  Old design  1.50


### Step 1: Define the null the alternative hypothesis

$H_{0}: \mu_{OldDesign} = \mu_{NewDesign}$

$H_{A}: \mu_{OldDesign} \neq \mu_{NewDesign}$


In this experiment, the null hypothesis assumes the average session time spent on the pages are equal and if there is a difference this is only due to the chance factor. In contrast, the alternative hypothesis assumes there is a statistically significant difference between the average session time.
### Step 2: Set Significance Level

$\alpha = 0.05$

### Step 3: Select the appropriate statistical test

#### What type of variable is the "input"?

The input is a binary classification, "old design" vs "new design". So, the answer is **Binary**

#### What type of variable is the "response"?

The response is "average session time," which is a **continuous** value

#### Is the response paired?

**No**, the responses are not paired by the groups; they are independent groups.

#### Does the response follow a normal distribution in both groups?

Need to either test for Normality with a Shapiro-Wilk hypothesis test, or assume normality based on other descriptive details of the data (sample size, skewness, etc.)

In [ ]:
old_design = design.loc[(design.Page == 'Old design')] #Survivors
old_design.describe()

            Time
count  21.000000
mean    1.435714
std     0.589734
min     0.350000
25%     0.900000
50%     1.500000
75%     1.900000
max     2.500000

In [ ]:
stats.shapiro(old_design['Time'])

(0.9582112431526184, 0.48085227608680725)

#### Since the p-value is large, we do not reject the null hypothesis. The   **time** is normally distributed. Therefore, we need to use a Student's t-test. Let's do the same for the next set

In [ ]:
new_design = design.loc[(design.Page == 'New design')] #Survivors
new_design.describe()

            Time
count  28.000000
mean    1.664286
std     0.645907
min     0.400000
25%     1.275000
50%     1.500000
75%     2.050000
max     2.900000

In [ ]:
stats.shapiro(new_design['Time'])

(0.9624826312065125, 0.398596853017807)

#### Are variances between groups equal?

Need to run an F-test to test for equal variances.

In [ ]:
#perform F-test
stats.f_oneway(old_design['Time'],new_design['Time'])

F_onewayResult(statistic=1.6172405295817571, pvalue=0.20973393181735653)

p-value > 0.05, so we **Fail To Reject the Null Hypothesis**. The variances are equal.
So, the appropriate statistical test to test our original hypothesis is a **Student's two-sample t-test**!

### Step 4: Decide One or Two Tailed

Two-tailed

### Step 5: Run the Statistical Test

In [ ]:
stats.ttest_ind(old_design['Time'],new_design['Time']) ## from scipy.stats

Ttest_indResult(statistic=-1.271707721759113, pvalue=0.20973393181735656)

p-value > 0.05, so we Fail To Reject the Null Hypothesis. **There is no difference in the session time of the new design and the old design**

## Thank you!!!

Let's connect! [LinkedIn](https://www.linkedin.com/in/angela-gaetano-m-s-5945043a/)